defmodule Taskmaster.Grocery.DefaultTerms do
  @moduledoc """
  The grocery words the board knows out of the box.

  Written as an explicit list of strings rather than `~w`, because `~w` splits on
  an escaped space as readily as a real one: `~w(hot\\ dog)` yields
  `["hot", "dog"]`, not `["hot dog"]`. Every multi-word term here was being
  shredded into fragments, and fragments like "hot" and "ice" then matched far
  more than they should.

  These are only **seed data**: migration 5 copies them into the `grocery_terms`
  table, and from then on `Taskmaster.Grocery.Dictionary` is the single source of
  truth. That is deliberate — a term nobody can delete would be indistinguishable
  from a bug once the family can edit the rest of the list.

  Editing this list therefore has no effect on an existing database. To change
  what a running board knows, edit the dictionary through the Groceries screen.
  """

  @meat_dairy [
    "milk",
    "cheese",
    "butter",
    "cream",
    "yogurt",
    "beef",
    "chicken",
    "pork",
    "lamb",
    "turkey",
    "bacon",
    "ham",
    "sausage",
    "steak",
    "eggs",
    "egg",
    "meat",
    "fish",
    "salmon",
    "tuna",
    "shrimp",
    "crab",
    "lobster",
    "veal",
    "duck",
    "goose",
    "bison",
    "venison",
    "mozzarella",
    "cheddar",
    "parmesan",
    "brie",
    "gouda",
    "ricotta",
    "cottage",
    "swiss",
    "provolone",
    "colby",
    "muenster",
    "havarti",
    "gruyere",
    "fontina",
    "mascarpone",
    "camembert",
    "feta",
    "halloumi",
    "paneer",
    "monterey",
    "pepper jack",
    "american",
    "velveeta",
    "queso",
    "tilapia",
    "cod",
    "catfish",
    "trout",
    "bass",
    "perch",
    "walleye",
    "mahi",
    "sardine",
    "anchovy",
    "herring",
    "mackerel",
    "swordfish",
    "halibut",
    "snapper",
    "grouper",
    "flounder",
    "sole",
    "clam",
    "mussel",
    "oyster",
    "scallop",
    "squid",
    "calamari",
    "octopus",
    "crawfish",
    "prawn",
    "ceviche",
    "lox",
    "gravlax",
    "pepperoni",
    "salami",
    "prosciutto",
    "capicola",
    "pancetta",
    "chorizo",
    "bratwurst",
    "kielbasa",
    "liverwurst",
    "bologna",
    "hot dog",
    "jerky",
    "corned beef",
    "pastrami",
    "roast beef",
    "ground beef",
    "ground turkey",
    "ground pork",
    "ribs",
    "tenderloin",
    "sirloin",
    "ribeye",
    "filet",
    "brisket",
    "flank",
    "skirt",
    "chuck",
    "roast",
    "drumstick",
    "thigh",
    "breast",
    "wing",
    "giblet",
    "liver",
    "kidney",
    "tongue",
    "tripe",
    "oxtail",
    "buttermilk",
    "kefir",
    "whey",
    "casein",
    "ghee",
    "lard",
    "tallow",
    "suet",
    "half and half",
    "whipping cream",
    "sour cream",
    "cream cheese",
    "ice cream",
    "custard",
    "pudding",
    "gelato",
    "frozen yogurt",
    "eggnog",
    "condensed milk",
    "evaporated milk",
    "powdered milk",
    "goat milk",
    "oat milk",
    "almond milk",
    "soy milk",
    "coconut milk"
  ]

  @produce [
    "apple",
    "banana",
    "orange",
    "lettuce",
    "tomato",
    "potato",
    "onion",
    "carrot",
    "broccoli",
    "pepper",
    "spinach",
    "cucumber",
    "celery",
    "garlic",
    "avocado",
    "lemon",
    "lime",
    "berry",
    "berries",
    "grapes",
    "grape",
    "mango",
    "pineapple",
    "watermelon",
    "cantaloupe",
    "honeydew",
    "peach",
    "pear",
    "plum",
    "cherry",
    "strawberry",
    "blueberry",
    "raspberry",
    "blackberry",
    "kiwi",
    "papaya",
    "coconut",
    "pomegranate",
    "fig",
    "date",
    "apricot",
    "nectarine",
    "tangerine",
    "grapefruit",
    "zucchini",
    "squash",
    "eggplant",
    "cabbage",
    "kale",
    "arugula",
    "radish",
    "turnip",
    "beet",
    "asparagus",
    "artichoke",
    "corn",
    "peas",
    "beans",
    "mushroom",
    "cilantro",
    "parsley",
    "basil",
    "mint",
    "dill",
    "rosemary",
    "thyme",
    "oregano",
    "ginger",
    "jalapeno",
    "habanero",
    "serrano",
    "poblano",
    "clementine",
    "mandarin",
    "kumquat",
    "lychee",
    "dragonfruit",
    "starfruit",
    "passionfruit",
    "guava",
    "persimmon",
    "jackfruit",
    "durian",
    "rambutan",
    "longan",
    "plantain",
    "breadfruit",
    "soursop",
    "boysenberry",
    "elderberry",
    "gooseberry",
    "cranberry",
    "currant",
    "acai",
    "goji",
    "mulberry",
    "blood orange",
    "cara cara",
    "navel",
    "satsuma",
    "tangelo",
    "ugli",
    "romaine",
    "iceberg",
    "bibb",
    "butterhead",
    "endive",
    "radicchio",
    "watercress",
    "chard",
    "collard",
    "bok choy",
    "napa",
    "fennel",
    "leek",
    "scallion",
    "shallot",
    "chive",
    "green onion",
    "ramp",
    "spring onion",
    "sweet potato",
    "yam",
    "parsnip",
    "rutabaga",
    "celeriac",
    "jicama",
    "taro",
    "cassava",
    "daikon",
    "kohlrabi",
    "sunchoke",
    "horseradish",
    "wasabi",
    "turmeric",
    "galangal",
    "lemongrass",
    "tamarind",
    "snow pea",
    "snap pea",
    "edamame",
    "lima",
    "fava",
    "chickpea",
    "lentil",
    "green bean",
    "wax bean",
    "kidney bean",
    "black bean",
    "pinto bean",
    "navy bean",
    "okra",
    "brussels sprout",
    "cauliflower",
    "broccolini",
    "rapini",
    "pumpkin",
    "acorn squash",
    "butternut",
    "spaghetti squash",
    "delicata",
    "kabocha",
    "bell pepper",
    "banana pepper",
    "cherry pepper",
    "scotch bonnet",
    "ghost pepper",
    "cayenne",
    "chipotle",
    "ancho",
    "guajillo",
    "pasilla",
    "anaheim",
    "hatch",
    "portobello",
    "shiitake",
    "oyster mushroom",
    "chanterelle",
    "morel",
    "porcini",
    "enoki",
    "cremini",
    "maitake",
    "truffle",
    "sage",
    "tarragon",
    "chervil",
    "marjoram",
    "lemon balm",
    "sorrel",
    "lovage",
    "epazote",
    "curry leaf",
    "bay leaf",
    "lavender",
    "chamomile",
    "sprout",
    "microgreen",
    "wheatgrass",
    "alfalfa",
    "bean sprout"
  ]

  @doc """
  Every built-in term as `{name, category}`, lowercased and deduplicated.
  """
  def all do
    for {terms, category} <- [{@meat_dairy, "meat_dairy"}, {@produce, "produce"}],
        term <- terms do
      {String.downcase(term), category}
    end
    # A word appearing in both lists keeps its first (meat & dairy) category,
    # matching how the old cond-based categoriser resolved the overlap.
    |> Enum.uniq_by(&elem(&1, 0))
  end
end
